exports.list = () => {
  return [
    {
      "id": "57328817_001",
      "sku": "57328817",
      "name": "Levi�s Corduroy Skate Overshirt",
      "category": "Tops",
      "price": "128.00",
      "brand": "Levi's",
      "color": "Black",
      "color_id": "001",
      "image_ids": [
        "57328817_001_b",
        "57328817_001_d",
        "57328817_001_e",
        "57328817_001_f",
        "57328817_001_g",
        "57328817_001_h"
      ],
      "sizes": ["XS", "S", "M", "L", "XL", "XXL"],
      "description": "Essential shirt jacket by Levi�s in a heavyweight 100% cotton cord fabrication with a button-down front. Topped with two flap pockets at the chest and cut with a straight hem.",
      "contents": "- 100% Cotton|- Machine wash|- Imported|- Measurements taken from size Medium|- Chest: 21�|- Length: 30�",
      "url": "https://www.urbanoutfitters.com/shop/levis-corduroy-skate-overshirt?color=001"
    },
    {
      "id": "56522410_004",
      "sku": "56522410",
      "name": "Nike Air Max 90 NRG Sneaker",
      "category": "Shoes",
      "price": "180.00",
      "brand": "Nike",
      "color": "Grey",
      "color_id": "004",
      "image_ids": [
        "56522410_004_b",
        "56522410_004_d",
        "56522410_004_e",
        "56522410_004_f"
      ],
      "sizes": [
        "M 7/W 8.5",
        "M 8/W 9.5",
        "M 9/W 10.5",
        "M 9.5/W 11",
        "M 10/W 11.5",
        "M 10.5/W 12",
        "M 11/W 12.5",
        "M 12/W 13.5",
        "M 13/W 14.5"
      ],
      "description": "The classic Air Max 90 sneaker with a throwback style. Low-profile silhouette runner with a lace-up front and equipped with Nike Air sole unit. Topped with branded detailing and finished with a waffle texture outsole.",
      "contents": "- Textile, leather, rubber|- Spot clean|- Imported",
      "url": "https://www.urbanoutfitters.com/shop/nike-air-max-90-nrg-sneaker?color=004"
    },
    {
      "id": "59231886_002",
      "sku": "59231886",
      "name": "Standard Cloth 3\" Oliver Nylon Short",
      "category": "Bottoms",
      "price": "34.00",
      "brand": "Standard Cloth",
      "color": "Washed Black",
      "color_id": "002",
      "image_ids": [
        "59231886_002_b",
        "59231886_002_d",
        "59231886_002_e",
        "59231886_002_f",
        "59231886_002_g",
        "59231886_002_h"
      ],
      "sizes": ["XS", "S", "M", "L", "XL"],
      "description": "Simple nylon shorts from Standard Cloth, exclusively available at UO. Cut in a relaxed fit that hits just above the knee, these shorts are rendered from lightweight nylon and topped with a stretchy elastic waistband with adjustable drawstring closure. Finished with front slip pockets and a single back patch pocket.",
      "contents": "- Nylon|- Machine wash|- Imported|- Measurements taken from size Medium|- Rise: 10\"|-Inseam: 3\"|- Leg opening: 13\"",
      "url": "https://www.urbanoutfitters.com/shop/standard-cloth-3-oliver-nylon-short?color=002"
    },
    {
      "id": "59231886_030",
      "sku": "59231886",
      "name": "Standard Cloth 3\" Oliver Nylon Short",
      "category": "Bottoms",
      "price": "34.00",
      "brand": "Standard Cloth",
      "color": "Green",
      "color_id": "030",
      "image_ids": [
        "59231886_030_b",
        "59231886_030_d",
        "59231886_030_e",
        "59231886_030_f",
        "59231886_030_g",
        "59231886_030_h"
      ],
      "sizes": ["XS", "S", "M", "L", "XL"],
      "description": "Simple nylon shorts from Standard Cloth, exclusively available at UO. Cut in a relaxed fit that hits just above the knee, these shorts are rendered from lightweight nylon and topped with a stretchy elastic waistband with adjustable drawstring closure. Finished with front slip pockets and a single back patch pocket.",
      "contents": "- Nylon|- Machine wash|- Imported|- Measurements taken from size Medium|- Rise: 10\"|-Inseam: 3\"|- Leg opening: 13\"",
      "url": "https://www.urbanoutfitters.com/shop/standard-cloth-3-oliver-nylon-short?color=030"
    },
    {
      "id": "58272097_040",
      "sku": "58272097",
      "name": "Fried Rice Zip Pullover Sweatshirt",
      "category": "Coats + Jackets",
      "price": "285.00",
      "brand": "Fried Rice",
      "color": "Blue",
      "color_id": "040",
      "image_ids": [
        "58272097_040_b",
        "58272097_040_d",
        "58272097_040_e",
        "58272097_040_f",
        "58272097_040_g",
        "58272097_040_h"
      ],
      "sizes": ["S", "M", "L", "XL"],
      "description": "Woven cotton pullover sweatshirt by Fried Rice featuring a lace-up & tie detail to the front. Fitted with a hood and includes pockets at the waist. Topped with a stripe pattern allover and finished with subtle fringe trims at the cuffs and hem.",
      "contents": "- 100% Cotton|- Machine wash|- Imported|- Measurements taken from size Medium|- Chest: 22�|- Length: 30�",
      "url": "https://www.urbanoutfitters.com/shop/fried-rice-zip-pullover-sweatshirt?color=040"
    },
    {
      "id": "56779259_041",
      "sku": "56779259",
      "name": "Fjallraven Vardag Tote Backpack",
      "category": "Accessories",
      "price": "70.00",
      "brand": "Fjallraven",
      "color": "Navy",
      "color_id": "041",
      "image_ids": [
        "56779259_041_b",
        "56779259_041_d",
        "56779259_041_e",
        "56779259_041_f",
        "56779259_041_g"
      ],
      "sizes": ["ONE SIZE"],
      "description": "Versatile tote pack by Fjallraven in a light and convenient silhouette for all your daily essentials. Made from durable G-1000 HeavyDuty Eco S with a reinforced base, featuring a main compartment with a padded laptop sleeve and quick-access pocket. The handles are combined with shoulder straps for convenient carrying. Lined with recycled nylon.",
      "contents": "- Polyester, cotton, nylon|- Spot clean|- Imported|- Length: 12�|- Width: 7�|- Height: 17�",
      "url": "https://www.urbanoutfitters.com/shop/fjallraven-vardag-tote-backpack3?color=041"
    },
    {
      "id": "57194300_001",
      "sku": "57194300",
      "name": "Mitchell & Ness Real Big Face Anthony Davis Tee",
      "category": "Tops",
      "price": "39.00",
      "brand": "Mitchell & Ness",
      "color": "Black",
      "color_id": "001",
      "image_ids": ["57194300_001_b", "57194300_001_d"],
      "sizes": ["S", "M", "L", "XL", "XXL"],
      "description": "Real Big Face tee from Mitchell & Ness, featuring a face graphic and signature of LA Lakers player, Anthony Davis. Cotton tee features a short sleeve silhouette with a relaxed fit and ribbed crew neck. Finished with an authentic Mitchell & Ness logo hit at the flat hem.",
      "contents": "- 100% Cotton|- Machine wash|- Imported|- Measurements taken from size Medium|- Chest: 20�|- Length: 28�",
      "url": "https://www.urbanoutfitters.com/shop/mitchell-and-ness-real-big-face-anthony-davis-tee?color=001"
    },
    {
      "id": "59718197_010",
      "sku": "59718197",
      "name": "Feiyue FE Lo 1920 Sneaker",
      "category": "Shoes",
      "price": "25.00",
      "brand": "Feiyue",
      "color": "White",
      "color_id": "010",
      "image_ids": [
        "59718197_010_b",
        "59718197_010_d",
        "59718197_010_e",
        "59718197_010_f",
        "59718197_010_g"
      ],
      "sizes": [
        "M 8",
        "M 7",
        "M 9",
        "M 9.5",
        "M 10",
        "M 10.5",
        "M 11",
        "M 12",
        "M 13"
      ],
      "description": "Classic sneaker by Feiyue features a plimsoll design that�s lightweight, simple and classic. Distinguished by its large rubber toe cap, canvas upper, molded insole and contrast logo.",
      "contents": "- Cotton, rubber|- Spot clean|- Imported",
      "url": "https://www.urbanoutfitters.com/shop/feiyue-fe-lo-1920-sneaker?color=010"
    },
    {
      "id": "58246281_040",
      "sku": "58246281",
      "name": "Altru Apparel Van Gogh Collegiate Hoodie Sweatshirt",
      "category": "Tops",
      "price": "69.00",
      "brand": "Altru Apparel",
      "color": "Blue",
      "color_id": "040",
      "image_ids": [
        "58246281_040_b",
        "58246281_040_d",
        "58246281_040_e",
        "58246281_040_f"
      ],
      "sizes": ["S", "M", "L", "XL", "XXL"],
      "description": "Jock meets artsy in this collegiate hoodie from Altru Apparel, featuring an arched text hit of your fav 19th-century artist across the chest. Pullover silhouette offers a cotton outer with light poly fleece lining. Topped with adjustable drawstring hood, front kanga pocket and rib-knit trim.",
      "contents": "- Cotton, polyester|- Machine wash|- Imported|- Measurements taken from size Medium|- Chest: 23�|- Length: 26�",
      "url": "https://www.urbanoutfitters.com/shop/altru-apparel-van-gogh-collegiate-hoodie-sweatshirt?color=040"
    },
    {
      "id": "56915861_001",
      "sku": "56915861",
      "name": "Patagonia Isthmus Hooded Parka",
      "category": "Coats + Jackets",
      "price": "249.00",
      "brand": "Patagonia",
      "color": "Black",
      "color_id": "001",
      "image_ids": [
        "56915861_001_b",
        "56915861_001_d",
        "56915861_001_e",
        "56915861_001_f",
        "56915861_001_g",
        "56915861_001_h"
      ],
      "sizes": ["XS", "S", "M", "L", "XL", "XXL"],
      "description": "Vintage-inspired parka from Patagonia in a wind and weather-resistant design. Long silhouette with a zip front and removable hood. Plush fleece lining. Made from all recycled fabrics and Fair Trade Certified.",
      "contents": "- 100% Recycled nylon|- Machine wash|- Imported|- Measurements taken from size Medium|- Chest: 22�|- Length: 29�",
      "url": "https://www.urbanoutfitters.com/shop/patagonia-isthmus-hooded-parka?color=001"
    },
    {
      "id": "56915861_040",
      "sku": "56915861",
      "name": "Patagonia Isthmus Hooded Parka",
      "category": "Coats + Jackets",
      "price": "249.00",
      "brand": "Patagonia",
      "color": "Blue",
      "color_id": "040",
      "image_ids": [
        "56915861_040_b",
        "56915861_040_d",
        "56915861_040_e",
        "56915861_040_f"
      ],
      "sizes": ["XS", "S", "M", "L", "XL"],
      "description": "Vintage-inspired parka from Patagonia in a wind and weather-resistant design. Long silhouette with a zip front and removable hood. Plush fleece lining. Made from all recycled fabrics and Fair Trade Certified.",
      "contents": "- 100% Recycled nylon|- Machine wash|- Imported|- Measurements taken from size Medium|- Chest: 22�|- Length: 29�",
      "url": "https://www.urbanoutfitters.com/shop/patagonia-isthmus-hooded-parka?color=040"
    },
    {
      "id": "56915861_072",
      "sku": "56915861",
      "name": "Patagonia Isthmus Hooded Parka",
      "category": "Coats + Jackets",
      "price": "249.00",
      "brand": "Patagonia",
      "color": "Yellow",
      "color_id": "072",
      "image_ids": [
        "56915861_072_b",
        "56915861_072_d",
        "56915861_072_e",
        "56915861_072_f"
      ],
      "sizes": ["XS", "S", "M", "L", "XL"],
      "description": "Vintage-inspired parka from Patagonia in a wind and weather-resistant design. Long silhouette with a zip front and removable hood. Plush fleece lining. Made from all recycled fabrics and Fair Trade Certified.",
      "contents": "- 100% Recycled nylon|- Machine wash|- Imported|- Measurements taken from size Medium|- Chest: 22�|- Length: 29�",
      "url": "https://www.urbanoutfitters.com/shop/patagonia-isthmus-hooded-parka?color=072"
    },
    {
      "id": "56965650_050",
      "sku": "56965650",
      "name": "Saucony Azura Sneaker",
      "category": "Shoes",
      "price": "90.00",
      "brand": "Saucony",
      "color": "Purple Multi",
      "color_id": "050",
      "image_ids": [
        "56965650_050_b",
        "56965650_050_d",
        "56965650_050_e",
        "56965650_050_f",
        "56965650_050_g"
      ],
      "sizes": [
        "M 7",
        "M 8",
        "M 9",
        "M 9.5",
        "M 10",
        "M 10.5",
        "M 11",
        "M 12",
        "M 13"
      ],
      "description": "Originally released in 1988, the Saucony Azura is back just in time to celebrate its 30th anniversary. Lightweight and fast runners offer a textile upper with suede overlays complete with the original torsional rigidity bar for optimal comfort and function. Finished with a rubber sole for grippy traction and the iconic Saucony branding at sides.",
      "contents": "- Suede, textile, rubber|- Spot clean|- Imported",
      "url": "https://www.urbanoutfitters.com/shop/saucony-azura-sneaker4?color=050"
    },
    {
      "id": "56965650_040",
      "sku": "56965650",
      "name": "Saucony Azura Sneaker",
      "category": "Shoes",
      "price": "90.00",
      "brand": "Saucony",
      "color": "Blue",
      "color_id": "040",
      "image_ids": [
        "56965650_040_b",
        "56965650_040_d",
        "56965650_040_e",
        "56965650_040_f",
        "56965650_040_g"
      ],
      "sizes": [
        "M 7",
        "M 8",
        "M 9",
        "M 9.5",
        "M 10",
        "M 10.5",
        "M 11",
        "M 12",
        "M 13"
      ],
      "description": "Originally released in 1988, the Saucony Azura is back just in time to celebrate its 30th anniversary. Lightweight and fast runners offer a textile upper with suede overlays complete with the original torsional rigidity bar for optimal comfort and function. Finished with a rubber sole for grippy traction and the iconic Saucony branding at sides.",
      "contents": "- Suede, textile, rubber|- Spot clean|- Imported",
      "url": "https://www.urbanoutfitters.com/shop/saucony-azura-sneaker4?color=040"
    },
    {
      "id": "54749064_010",
      "sku": "54749064",
      "name": "Birkenstock Arizona Core Sandal",
      "category": "Shoes",
      "price": "100.00",
      "brand": "Birkenstock",
      "color": "White",
      "color_id": "010",
      "image_ids": [
        "54749064_010_b",
        "54749064_010_d",
        "54749064_010_e",
        "54749064_010_f",
        "54749064_010_g"
      ],
      "sizes": ["M 7", "M 8", "M 9", "M 10", "M 11", "M 12", "M 13"],
      "description": "Classic slide sandal from the comfort legends of Birkenstock. Magical contoured cork foot bed and soft leather upper conforms to the shape of your foot for a custom fit as effortless as the design. Pronounced arch support with a layer of foam cushioning, deep heel cup and roomy toe box.",
      "contents": "- Leather, rubber|- Spot clean|- Imported",
      "url": "https://www.urbanoutfitters.com/shop/birkenstock-arizona-core-sandal?color=010"
    },
    {
      "id": "57726507_004",
      "sku": "57726507",
      "name": "Native Youth Reid Corduroy Jumpsuit",
      "category": "Bottoms",
      "price": "190.00",
      "brand": "Native Youth",
      "color": "Grey",
      "color_id": "004",
      "image_ids": [
        "57726507_004_b",
        "57726507_004_d",
        "57726507_004_e",
        "57726507_004_f",
        "57726507_004_g",
        "57726507_004_h"
      ],
      "sizes": ["S", "M", "L", "XL"],
      "description": "Button-through jumpsuit by Native Youth in a textured cord fabrication with long sleeve, tab collar & belted waist. Topped with classic pocket detailing and finished with tapered legs.",
      "contents": "- Imported",
      "url": "https://www.urbanoutfitters.com/shop/native-youth-reid-corduroy-jumpsuit?color=004"
    },
    {
      "id": "57316002_031",
      "sku": "57316002",
      "name": "adidas Zone Aeroready Pant",
      "category": "Bottoms",
      "price": "90.00",
      "brand": "adidas",
      "color": "Olive",
      "color_id": "031",
      "image_ids": [
        "57316002_031_b",
        "57316002_031_d",
        "57316002_031_e",
        "57316002_031_f"
      ],
      "sizes": ["XS", "S", "M", "L", "XL"],
      "description": "Aeroready pants from adidas. Climalite construction wicks sweat to keep you dry in every condition while front slip pockets are spacious enough to hold key items. Pull-on silhouette is cut with tapered legs are cut slim but offer a roomy, comfortable fit. Finished with branded hit at the left leg and colorblocking throughout.",
      "contents": "- 100% Polyester|- Machine wash|- Imported|- Measurements taken from size Medium|- Rise: 11�|- Inseam: 29�|- Leg opening: 5.75�",
      "url": "https://www.urbanoutfitters.com/shop/adidas-zone-aeroready-pant?color=031"
    },
    {
      "id": "54737770_001",
      "sku": "54737770",
      "name": "Hanes UO Exclusive Beefy Tee",
      "category": "Tops",
      "price": "25.00",
      "brand": "Hanes",
      "color": "Black",
      "color_id": "001",
      "image_ids": [
        "54737770_001_b",
        "54737770_001_d",
        "54737770_001_e",
        "54737770_001_f",
        "54737770_001_g"
      ],
      "sizes": ["S", "M", "L", "XL", "XXL"],
      "description": "Classic Hanes tee meets Beefy branded hit. Cotton construction is cut in a standard fit and topped with short sleeves and a ribbed crew neck. Finished with embroidered Beefy Tee logo at the chest. Get it exclusively at Urban Outfitters!",
      "contents": "- 100% Cotton|- Machine wash|- Imported|- Model in Black is 5�10� and wearing size Medium|- Measurements taken from size Medium|- Chest: 20�|- Length: 27�",
      "url": "https://www.urbanoutfitters.com/shop/hanes-uo-exclusive-beefy-tee?color=001"
    },
  ]
}
